version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_myapp_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - myapp_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_myapp_container
    environment:
      PMA_HOST: mariadb_myapp_container
      PMA_USER: user
      PMA_PASSWORD: userpassword
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mariadb

volumes:
  myapp_data:
